### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by FerDR89** [PabloMur/desafio8#1]
Buenas Pablo, espero que estes muy bien.

El desafío esta muy bien logrado, lo que hiciste con mapbox quedo muy bueno pero creo que hay cosas que se podrían mejorar y otras que son solicitadas directamente en el figma:

Debería de verse solo la imagen que cargue, lo otro estaría bueno que lo ocultes o deshabilites

![image](https://user-images.githubusercontent.com/74626765/224487257-c4dc02c9-15c7-474c-bd6f-a9b1a903476d.png)

Donde reportas la mascota, el input del search queda sobre el margen izquierdo

![image](https://user-images.githubusercontent.com/74626765/224487581-3dd08652-8f0e-430e-8b7f-cfaa93adebb6.png)

(Ejemplo)
![image](https://user-images.githubusercontent.com/74626765/224487556-828fccbd-f26c-4365-82b0-1ab16c4a56f8.png)

El desplegable estaría bueno que cuando toco un link y me redirecciona el mismo se cierre, como así tambien que quede el nombre del usuario logeado arriba del boton logout

![image](https://user-images.githubusercontent.com/74626765/224487731-a77bd807-ac7a-4ef8-8682-18f137f8dbd7.png)

Cuando quiero editar una mascota, los botones para confirmar o cancelar no se ven muy bien

![image](https://user-images.githubusercontent.com/74626765/224487995-89e87748-fc93-4678-9c5b-5bc6a50b5269.png)

Una vez que termine de testear todo, me desloguie y cuando puse encontrar mascotas cercanas no me figuran las que reporte 

![image](https://user-images.githubusercontent.com/74626765/224488064-17999580-f66e-4890-ada5-35416ad077ae.png)

Ahí vi que tengo que ingresar en el mapa la ubicación donde creo que están las mascotas perdidas para que me devuelva algo (En mobile se rompe la UI).

![image](https://user-images.githubusercontent.com/74626765/224488265-584c3d6c-ca2a-4bb0-980d-bf00b2aa2dbb.png)

**Comment by PabloMur** [comment]
Joya Fer, ni bien termine con los fixes lo mando de nuevo
